apiVersion: apps/v1
kind: Deployment
metadata:
  name: reaper-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: reaper-operator
  template:
    metadata:
      labels:
        name: reaper-operator
    spec:
      serviceAccountName: reaper-operator
      containers:
        - name: reaper-operator
          # Replace this with the built image name
          image: docker.io/thelastpickle/reaper-operator:latest
          command:
          - reaper-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "reaper-operator"
