name: Go

on:
  push:
    branches:
      - master
      - e2e-kind-debug

  pull_request:
    branches: [ master ]

jobs:
  build_operator_image:
    name: Build reaper-operator image
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/go
      GOROOT: /usr/local/go1.13
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run unit tests
        run: |
          export PATH=$GOROOT/bin:$GOPATH/bin:$PATH
          make test
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.io --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push image
        run: make docker-build docker-push

      - name: Install kubectl
        run: |
          curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.19.0/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Install kind
        run: go get sigs.k8s.io/kind@v0.7.0

      - name: Run e2e tests
        run: |
          kind create cluster --name reaper
          export KUBECONFIG="$(kind get kubeconfig-path --name="reaper")"
          make e2e-test